<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecommendedPlaceSeeder extends Seeder
{
    public function run(): void
    {
        // DB::table('recommended_places')->insert([
        //     // Nature & Landmarks
        //     [
        //         'name' => 'Chocolate Hills',
        //         'description' => 'Bohol\'s most iconic geological formation featuring over 1,200 grass-covered limestone hills that turn chocolate brown during the dry season. A UNESCO World Heritage Site candidate.',
        //         'latitude' => 9.916700,
        //         'longitude' => 124.133300,
        //         'image_url' => 'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/07/38/d7/7c.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Alona Beach',
        //         'description' => 'Stunning white sand beach on Panglao Island famous for crystal clear waters, vibrant nightlife, world-class diving, and numerous beach resorts.',
        //         'latitude' => 9.548889,
        //         'longitude' => 123.773056,
        //         'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/13/7f/73/alona-beach.jpg',
        //         'category' => 'Beach',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Philippine Tarsier Sanctuary',
        //         'description' => 'Protected sanctuary in Corella where visitors can see the tiny Philippine Tarsier (one of the world\'s smallest primates) in their natural habitat.',
        //         'latitude' => 9.687222,
        //         'longitude' => 123.952222,
        //         'image_url' => 'https://www.tarsiersanctuary.com.ph/wp-content/uploads/2020/05/tarsier-sanctuary.jpg',
        //         'category' => 'Wildlife',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Loboc River Cruise',
        //         'description' => 'Peaceful river cruise along the Loboc River featuring floating restaurants with buffet dining, live acoustic music, and scenic views of lush tropical vegetation.',
        //         'latitude' => 9.638056,
        //         'longitude' => 124.034722,
        //         'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/f7/1c/3d/loboc-river-cruise.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Hinagdanan Cave',
        //         'description' => 'Spectacular limestone cave with stunning stalactite and stalagmite formations, featuring a natural underground pool perfect for swimming.',
        //         'latitude' => 9.620278,
        //         'longitude' => 123.769444,
        //         'image_url' => 'https://live.staticflickr.com/8239/8511181696_1e5af474b2_b.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Bilar Man-Made Forest',
        //         'description' => 'A stunning 2-kilometer stretch of densely planted Mahogany trees along the road between Bilar and Loboc, creating a beautiful green tunnel.',
        //         'latitude' => 9.708889,
        //         'longitude' => 124.103889,
        //         'image_url' => 'https://live.staticflickr.com/65535/50909232498_3bfb5ac790_b.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Baclayon Church',
        //         'description' => 'One of the oldest stone churches in the Philippines, built in 1727 by Jesuit priests. Features a museum with religious artifacts and centuries-old relics.',
        //         'latitude' => 9.622222,
        //         'longitude' => 123.911667,
        //         'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/4/47/Baclayon_Church_Facade.jpg',
        //         'category' => 'Historical',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Blood Compact Shrine',
        //         'description' => 'Historical site marking the blood compact between Spanish explorer Miguel López de Legazpi and Datu Sikatuna in 1565, symbolizing friendship and peace.',
        //         'latitude' => 9.642222,
        //         'longitude' => 123.858333,
        //         'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Blood_Compact_Shrine.jpg',
        //         'category' => 'Historical',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Danao Adventure Park',
        //         'description' => 'Extreme adventure destination offering activities like zipline, cable car, suislide, and the famous "Plaza Rizal" extreme swing.',
        //         'latitude' => 9.945278,
        //         'longitude' => 124.243889,
        //         'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/12/a5/56/danao-adventure-park.jpg',
        //         'category' => 'Adventure',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Panglao Island',
        //         'description' => 'Famous island paradise known for its white sand beaches, diving spots, luxury resorts, and the iconic Hinagdanan Cave.',
        //         'latitude' => 9.578889,
        //         'longitude' => 123.765833,
        //         'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0a/0e/3f/32/panglao-island.jpg',
        //         'category' => 'Beach',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Mag-Aso Falls',
        //         'description' => 'Multi-tiered waterfall in Antequera with cool, turquoise waters perfect for swimming and picnicking surrounded by lush greenery.',
        //         'latitude' => 9.760278,
        //         'longitude' => 123.936389,
        //         'image_url' => 'https://live.staticflickr.com/8632/16363277762_5f20b13c96_b.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Cambugahay Falls',
        //         'description' => 'Stunning three-tiered waterfall in Lazi with turquoise blue waters, natural swimming pools, and rope swings for jumping into the water.',
        //         'latitude' => 9.130556,
        //         'longitude' => 123.634444,
        //         'image_url' => 'https://live.staticflickr.com/4230/35118753251_7ebd23e213_b.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Balicasag Island',
        //         'description' => 'Marine sanctuary famous for world-class diving and snorkeling, featuring sea turtles, colorful coral reefs, and diverse marine life.',
        //         'latitude' => 9.516667,
        //         'longitude' => 123.683333,
        //         'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/04/d9/9e/06/balicasag-island.jpg',
        //         'category' => 'Beach',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Virgin Island',
        //         'description' => 'Sandbar island near Panglao that emerges during low tide, featuring powdery white sand and crystal clear shallow waters.',
        //         'latitude' => 9.576389,
        //         'longitude' => 123.724722,
        //         'image_url' => 'https://live.staticflickr.com/4459/37669783882_5f3aed66c1_b.jpg',
        //         'category' => 'Beach',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Dumaluan Beach',
        //         'description' => 'Less crowded white sand beach on Panglao with gentle sloping shore, ideal for swimming and family outings.',
        //         'latitude' => 9.559722,
        //         'longitude' => 123.770278,
        //         'image_url' => 'https://live.staticflickr.com/5529/12059477463_9ea5f57dac_b.jpg',
        //         'category' => 'Beach',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Panglao Church',
        //         'description' => 'Historic church in Panglao town featuring a unique watchtower and beautiful coral stone architecture built in the 18th century.',
        //         'latitude' => 9.587500,
        //         'longitude' => 123.748056,
        //         'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/8/80/Panglao_Church.jpg',
        //         'category' => 'Historical',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Dimiao Twin Falls',
        //         'description' => 'Two beautiful waterfalls in Dimiao featuring natural swimming pools surrounded by limestone formations and tropical vegetation.',
        //         'latitude' => 9.626389,
        //         'longitude' => 124.171389,
        //         'image_url' => 'https://live.staticflickr.com/65535/50909232498_3bfb5ac790_b.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Bohol Bee Farm',
        //         'description' => 'Organic farm and resort featuring bee-keeping demonstrations, organic restaurant, spa, and stunning ocean views.',
        //         'latitude' => 9.532778,
        //         'longitude' => 123.752222,
        //         'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/b7/5a/7f/bohol-bee-farm.jpg',
        //         'category' => 'Eco-tourism',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Clarin Ancestral House',
        //         'description' => 'Well-preserved Spanish-era ancestral house in Loay showcasing Filipino-Spanish architecture and antique furniture.',
        //         'latitude' => 9.579722,
        //         'longitude' => 123.926111,
        //         'image_url' => 'https://live.staticflickr.com/4047/4350775944_d1959a7d9e_b.jpg',
        //         'category' => 'Historical',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Pamilacan Island',
        //         'description' => 'Whale and dolphin watching destination featuring pristine beaches, historical Spanish fort, and marine sanctuary.',
        //         'latitude' => 9.516667,
        //         'longitude' => 124.266667,
        //         'image_url' => 'https://live.staticflickr.com/1461/25774156044_8b63a7d12d_b.jpg',
        //         'category' => 'Beach',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Cabagnow Cave Pool',
        //         'description' => 'Hidden cave pool in Anda featuring clear blue waters inside a limestone cave, perfect for cliff jumping and swimming.',
        //         'latitude' => 9.714444,
        //         'longitude' => 124.592778,
        //         'image_url' => 'https://live.staticflickr.com/8262/29112040082_8b95db06f7_b.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Lamanok Island',
        //         'description' => 'Mystical island in Anda known for its ancient cave paintings, burial sites, and mysterious rock formations.',
        //         'latitude' => 9.666667,
        //         'longitude' => 124.566667,
        //         'image_url' => 'https://live.staticflickr.com/620/20611013643_8a3f1297c0_b.jpg',
        //         'category' => 'Historical',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Alicia Panoramic Park',
        //         'description' => 'Hilltop park offering stunning 360-degree views of Bohol\'s countryside, chocolate hills, and nearby islands.',
        //         'latitude' => 9.866667,
        //         'longitude' => 124.450000,
        //         'image_url' => 'https://live.staticflickr.com/4509/23918520608_55cf8f0df6_b.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Can-olin Falls',
        //         'description' => 'Hidden waterfall in Jagna featuring cold, clear waters and a natural swimming hole surrounded by rock formations.',
        //         'latitude' => 9.645278,
        //         'longitude' => 124.371944,
        //         'image_url' => 'https://live.staticflickr.com/8557/28408205146_5137ad40c4_b.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Badiang Spring',
        //         'description' => 'Natural spring resort in Valencia featuring cold, crystal clear waters from underground springs perfect for swimming.',
        //         'latitude' => 9.639722,
        //         'longitude' => 124.196111,
        //         'image_url' => 'https://live.staticflickr.com/7237/7177112149_6c5d6ed0ef_b.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Sipatan Twin Hanging Bridges',
        //         'description' => 'Iconic bamboo hanging bridges in Jagna offering scenic views of the river and surrounding tropical landscape.',
        //         'latitude' => 9.655833,
        //         'longitude' => 124.364444,
        //         'image_url' => 'https://live.staticflickr.com/4162/34186935203_d70446f8f8_b.jpg',
        //         'category' => 'Adventure',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'St. Monica Church (Panglao)',
        //         'description' => 'Historic church built in 1850 featuring coral stone architecture and a unique bell tower with watchtower.',
        //         'latitude' => 9.587500,
        //         'longitude' => 123.748056,
        //         'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/8/80/Panglao_Church.jpg',
        //         'category' => 'Historical',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Butan Twin Falls',
        //         'description' => 'Two impressive waterfalls in San Isidro featuring strong water flow and natural pools for swimming.',
        //         'latitude' => 9.952500,
        //         'longitude' => 124.345278,
        //         'image_url' => 'https://live.staticflickr.com/475/19903029171_b9dae1db82_b.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Bohol Python Sanctuary',
        //         'description' => 'Home to the famous 25-foot python called "Prony" along with other snakes and reptile species in a natural setting.',
        //         'latitude' => 9.603889,
        //         'longitude' => 124.001389,
        //         'image_url' => 'https://live.staticflickr.com/3819/11924227476_21d187707f_b.jpg',
        //         'category' => 'Wildlife',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        //     [
        //         'name' => 'Pahangog Falls',
        //         'description' => 'Hidden waterfall in Dimiao featuring multiple cascades and natural pools surrounded by lush vegetation.',
        //         'latitude' => 9.626389,
        //         'longitude' => 124.171389,
        //         'image_url' => 'https://live.staticflickr.com/8557/28408205146_5137ad40c4_b.jpg',
        //         'category' => 'Nature',
        //         'is_active' => true,
        //         'created_at' => now(),
        //         'updated_at' => now(),
        //     ],
        // ]);


        DB::table('recommended_places')->insert([
            [
                'name' => 'Chocolate Hills',
                'description' => 'Bohol’s most iconic landscape with over 1,200 symmetrical hills that turn brown during the dry season.',
                'latitude' => 9.80000000,
                'longitude' => 124.16666600,
                'image_url' => 'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/07/38/d7/7c.jpg',
                'category' => 'Nature',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alona Beach',
                'description' => 'A famous white sand beach in Panglao known for clear waters, nightlife, and diving spots.',
                'latitude' => 9.54888800,
                'longitude' => 123.77305600,
                'image_url' => 'https://philippineshiddengems.com/wp-content/uploads/2025/01/Alona-Beach-in-Bohol-Philippines-during-daytime.jpg',
                'category' => 'Beach',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tarsier Sanctuary (Corella)',
                'description' => 'A protected area where you can see the world’s smallest primates in their natural habitat.',
                'latitude' => 9.68722200,
                'longitude' => 123.95222200,
                'image_url' => 'https://cdn.forevervacation.com/uploads/attraction/philippine-tarsier-sanctuary-2700.jpg',
                'category' => 'Wildlife',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Loboc River Cruise',
                'description' => 'A relaxing river cruise with buffet dining and live music along the scenic Loboc River.',
                'latitude' => 9.63805600,
                'longitude' => 124.03472200,
                'image_url' => 'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/10/08/11/9a.jpg',
                'category' => 'Nature',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hinagdanan Cave',
                'description' => 'A beautiful limestone cave with a natural underground pool located in Panglao.',
                'latitude' => 9.62027800,
                'longitude' => 123.76944400,
                'image_url' => 'https://hinagdanancave.com/assets/images/hinagdanan-cave-1024x559.jpg',
                'category' => 'Nature',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bilar Man-Made Forest',
                'description' => 'A stunning 2-kilometer stretch of densely planted Mahogany trees along the road between Bilar and Loboc, creating a beautiful green tunnel.',
                'latitude' => 9.708889,
                'longitude' => 124.103889,
                'image_url' => 'https://bohol-philippines.com/wp-content/uploads/2025/07/man-made-forest.jpg',
                'category' => 'Nature',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baclayon Church',
                'description' => 'One of the oldest stone churches in the Philippines, built in 1727 by Jesuit priests. Features a museum with religious artifacts and centuries-old relics.',
                'latitude' => 9.622222,
                'longitude' => 123.911667,
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTU1idtLUF8SamaCwdVkIQsQpAb5hQXxAALIg&s',
                'category' => 'Historical',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blood Compact Shrine',
                'description' => 'Historical site marking the blood compact between Spanish explorer Miguel López de Legazpi and Datu Sikatuna in 1565, symbolizing friendship and peace.',
                'latitude' => 9.642222,
                'longitude' => 123.858333,
                'image_url' => 'https://aroundbohol.com/wp-content/uploads/2017/05/blood-compact-IMG_5905-2.jpg',
                'category' => 'Historical',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Danao Adventure Park',
                'description' => 'Extreme adventure destination offering activities like zipline, cable car, suislide, and the famous "Plaza Rizal" extreme swing.',
                'latitude' => 9.945278,
                'longitude' => 124.243889,
                'image_url' => 'https://bohol-philippines.com/wp-content/uploads/2025/08/108781-private-danao-adventure-park-day-tour-03.webp',
                'category' => 'Adventure',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Panglao Island',
                'description' => 'Famous island paradise known for its white sand beaches, diving spots, luxury resorts, and the iconic Hinagdanan Cave.',
                'latitude' => 9.578889,
                'longitude' => 123.765833,
                'image_url' => 'https://res.klook.com/image/upload/w_500,h_313,c_fill,q_85/activities/gvawpxgytvec6pxqneb8.jpg',
                'category' => 'Beach',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}